version: "3"

services:
  mapp-localstack:
    image: localstack/localstack:0.10.9
    container_name: mapp-localstack
    ports:
      - "4567-4597:4567-4597"
      - "8010:8010"
    environment:
      - SERVICES=sns
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8010
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-southeast-1
    volumes:
      - my-datavolume:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  my-datavolume:
